### ISSUE TITLE
toHaveCss fails on height: 'auto'

### ISSUE THREAD

**Issue by stewartknapman** [velesin/jasmine-jquery#147]
`expect($('<div style="height: auto;"></div>')).toHaveCss({height: "auto"});` is failing tests. Is this expected?

![screen shot 2013-09-25 at 5 06 49 pm](https://f.cloud.github.com/assets/1373290/1206879/6772b94e-25a0-11e3-951f-4ec4b1cf5d26.png)

**Comment by top-master** [comment]
The reason why jQuery changed to returning a computed value is that it's consistent across all browsers.

It's impossible to reliably determine if a CSS property will return "`auto`" across all browsers.
>I tested with JQuery 3.3.1, and `$(...).css(...)` returns the numerical computed value (which is `0px` for `auto`).
>```
>alert(`Version: ${jQuery.fn.jquery} Returns:\n`
>  + jQuery('<div style="height: auto;"></div>').css('height'));
>```
