### ISSUE TITLE
 TypeError: 'undefined' is not a function (evaluating 'jasmine.addMatchers')

### ISSUE THREAD

**Issue by br1anchen** [velesin/jasmine-jquery#168]
I am using yeoman angular-generator to set up the project, then by default it is using karma runner to make the unit test. The problem is after includes the jasmine-jquery pulgin, the karma unit test does not work.
The error message is : 

TypeError: 'undefined' is not a function (evaluating 'jasmine.addMatchers')
at ../app/bower_components/jasmine-jquery/lib/jasmine-jquery.js:716
at ../node_modules/karma-jasmine/lib/adapter.js:166

Here is my karma.conf.js:

module.exports = function(config) {
  config.set({

```
basePath: '',

frameworks: ['jasmine'],

files: [
  'app/bower_components/jquery/jquery.js',
  'app/bower_components/jasmine-jquery/lib/jasmine-jquery.js',
  'app/bower_components/angular/angular.js',
  'app/bower_components/angular-mocks/angular-mocks.js',
  'app/bower_components/angular-resource/angular-resource.js',
  'app/bower_components/angular-cookies/angular-cookies.js',
  'app/bower_components/angular-bootstrap/ui-bootstrap.js',
  'app/bower_components/angular-route/angular-route.js',
  'app/bower_components/angular-ui-router/release/angular-ui-router.js',
  'app/bower_components/node-uuid/uuid.js',
  'app/bower_components/x2js/xml2json.js',

  'app/scripts/config/App_Constants.js',
  'app/scripts/*.js',
  'app/scripts/**/*.js',
  'test/spec/**/*.js'
],

exclude: [],

reporters: ['progress'],

port: 8080,

logLevel: config.LOG_INFO,

autoWatch: true,

browsers: ['PhantomJS'],

singleRun: false
```

  });
};

I installed the karma-jasmine by npm, the only thing I would mentioned is all the bower_components arein the app directory by yeoman grunt configuration. If I put all the bower_components on the root directory of the project with bower.json (since in the yeoman generator it use .bowerrc file to redirect the install directory to app/bower_components which I would like to keep), then the test will work. So the only difference is the bower_components place. I have a guess with npm package place which is also under the root directory, would it be the case? But anyway I want to ask for a good solution for that, since I think the directory structure of yeoman workflow is quite good way to start :) 

PS: I am using jasmine-jquery 2.0.0 and karma-jasmine 0.1.5

**Comment by nathantechie9** [comment]
Is this issue back again?
