### ISSUE TITLE
Please mention OSX fix for issue #4 in documentation

### ISSUE THREAD

**Issue by tararoys** [velesin/jasmine-jquery#179]
[Referencing issue #81](https://github.com/velesin/jasmine-jquery/issues/81) 

Trying to run Chrome on OSX with the flag mentioned in the "Cross domain policy problems under Chrome" section of the README. resulted in the following error: 

```
 > /Applications/GoogleChrome.app/Contents/MacOS/GoogleChrome --allow-file-access-from-files SpecRunner.html 
 [29978:2819:0211/221357:ERROR:process_singleton_mac.cc(103)] Unable to obtain profile lock.
```

After three solid hours of debugging, the magic solution was to close Chrome entirely.  Without an instance of Chrome running, the profile lock (not [certain what a profile lock is, but this guy seems to know](http://bridge.grumpy-troll.org/2012/06/chrome-profiles/) is no longer a problem, and you can run the command: 

```
 >/Applications/GoogleChrome.app/Contents/MacOS/GoogleChrome --allow-file-access-from-files SpecRunner.html 
```

And Chrome will allow you to load fixtures just fine. 

note: for people who are trying to use the path /Applications/GoogleChrome.app/Contents/MacOS/GoogleChrome to launch Google Chrome, be warned that the spaces in the default name annoyed me so  renamed "Google Chrome" to GoogleChrome. You probably want to check to see what your personal pathname is.

**Comment by cameronjroe** [comment]
This feels super hacky.. is there no better way to build this into the library?
