### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by cburgmer** [velesin/jasmine-jquery#183]
It would be nice if jasmine-jquery was available over npm. Currently only some old fork is available there.

**Comment by varemenos** [comment]
Is this issue still valid?

**Comment by Nate-Wilkins** [comment]
@dkastner Thanks!

@varemenos  I don't think so

**Comment by WouterJ** [comment]
The latest 2.1 version is not available on NPM

**Comment by alexandernst** [comment]
+1, can we get 2.1.0 in npm?

**Comment by travisjeffery** [comment]
Just published 2.1.0 to npm
