### ISSUE TITLE
Does not play nicely with JQuery noConflict

### ISSUE THREAD

**Issue by freon27** [velesin/jasmine-jquery#198]
I can see that in 1.3, the code was updated to use jQuery() function instead of $() which meant it worked when noConflict was used.  The recent versions use $() again so it is not compatible.   Is there a reason for the switch back?  I'd rather not have to use very old code just for compatibility purposes.

**Comment by travisjeffery** [comment]
yeah like @Markionium this issue doesn't make sense if your js is working like it's supposed to
