### ISSUE TITLE
package.json main field

### ISSUE THREAD

**Issue by bornkiller** [velesin/jasmine-jquery#206]
Hi: 
I am working on karma-jasmine-jquery,(https://github.com/bornkiller/karma-jasmine-jquery.git), to make jasmine-jquery a karma plugin for convenience with karma test. so can you add 
```javascript
   "main": "lib/jasmine-jquery.js"
``` 
in your package.json, which I don't have to use an ugly way to achieve the plugin.

**Comment by attila** [comment]
+1 for this, with the "main" field added in package.json it would be possible to use `require.resolve('jasmine-jquery')` and similar and the likes.

**Comment by SimenB** [comment]
@travisjeffery Could you fix this now as you publish it on npm now? :smile:
