### ISSUE TITLE
Issue in migrating to jasmine 1.3 to 2.0

### ISSUE THREAD

**Issue by KiruthikaKumar** [velesin/jasmine-jquery#208]
Hi All,
I have included jasmine-jquery.js. 
I have installed jasmine 2.0.1 I am getting error like 
 TypeError: 'undefined' is not a function (evaluating '$('#' + this.containerId')

Please help me in resolving this error
Thanks

**Comment by travisjeffery** [comment]
i think @mattisa has the answer to OP's problem, gonna close since OP hasn't responded in a long time
