### ISSUE TITLE
Requires jQuery 1.8 or newer for jQuery.parseHTML

### ISSUE THREAD

**Issue by shakerlxxv** [velesin/jasmine-jquery#219]
While developing tests for an environment which uses jQuery 1.7.1, I encounter the following error when loading fixtures:

	TypeError: undefined is not a function
	    at jasmine.Fixtures.loadFixtureIntoCache_ (spec/javascripts/helpers/jasmine-jquery.js:135:25)

This comes from the use of `$.parseHTML(htmlText, true)`. According to the [API Doc](http://api.jquery.com/jQuery.parseHTML), this function was not available before jQuery 1.8, and this application should be equivalent to `$(htmlText)` which would work fine in older jQuery versions in most cases. So changing the line to

    var scripts = $(htmlText).find('script[src]') || [];

could eliminate the dependence on jQuery 1.8 or newer. It does look like there was a bug with `$(htmlText)` in the case where `htmlText` contained a leading space. So other options would be

1. The method used could depend first on `$.parseHTML` being defined or not.
2. If it remains as is with `$.parseHTML`, then adding a note about the jQuery version requirement to the **README.md** might help others encountering this issue.

**Comment by benbrowning** [comment]
+1 - I hit this issue too, upgrading jquery is not really an option so probably going to stick with an older version of jasmine-jquery.

**Comment by fortywinkz** [comment]
I have exctracted [`jQuery.parseHTML`](https://gist.github.com/fortywinkz/dafb710a24e9c35e749d) function from jquery 1.8+ and use it with other helpers for such case.

**Comment by benbrowning** [comment]
Thanks @fortywinkz I made use of that :)

**Comment by travisjeffery** [comment]
see our dependencies docs: https://github.com/velesin/jasmine-jquery#dependencies
