### ISSUE TITLE
Load jquery matchers in BeforeAll

### ISSUE THREAD

**Issue by SirLenz0rlot** [velesin/jasmine-jquery#226]
Hi,

From jasmine >2.1.0, the `beforeAll` is supported. 
Unfortunately, I was trying to use a custom matcher in my `beforeAll` (a simple sanity check), but since beforeAll is being called before beforeEach, the custom matchers from jasmine jquery dont seem to have loaded yet (..undefined not a function-errors).

Perhaps (haven't validated it) simply loading it in a beforeAll as well would help?!
because I think it could be a general jasmine issue, also see https://github.com/jasmine/jasmine/issues/721

**Comment by travisjeffery** [comment]
yea that's how jasmine works unfortunately
