### ISSUE TITLE
Tag 2.1.0 file has incorrect version in source file.

### ISSUE THREAD

**Issue by squaresurf** [velesin/jasmine-jquery#253]
https://raw.githubusercontent.com/velesin/jasmine-jquery/2.1.0/lib/jasmine-jquery.js

As you can see :point_up: the version states 2.0.7 when the tag is actually for 2.1.0.

**Comment by travisjeffery** [comment]
Ah woops, I have a Grunt task to update it which must've not have gotten run last time. Will do next time thanks!

**Comment by loginx** [comment]
The tag would also need to be fixed, since it's what bower uses. https://github.com/velesin/jasmine-jquery/blob/2.1.0/lib/jasmine-jquery.js
