### ISSUE TITLE
Karma serve files under a `/base' directory

### ISSUE THREAD

**Issue by teone** [velesin/jasmine-jquery#264]
Hi @velesin and thanks a lot for this wonderful library.

I've [noticed](http://stackoverflow.com/questions/28562448/jasmine-jquery-wont-load-any-fixture) that `Karma` as default serve files under a `/base` directory, and this let me be stucked for a couple of hours.

Should we add a note in the README section about 'fixturesPath' ?

**Comment by travisjeffery** [comment]
Yeah feel free to make a PR

**Comment by teone** [comment]
Done here: 45d26293542ad911bc9a4f141659743d81ae1b50

**Comment by teone** [comment]
Readme has been updated
