### ISSUE TITLE
How to check whether the jquery plugin is applied to the DOM element?

### ISSUE THREAD

**Issue by sadikr** [velesin/jasmine-jquery#298]
Consider a scenario where I am applying a datepicker plugin to a input#myDatePickerInput and would like to check something like

spyOn($.fn, "datepciker");
expect($.fn.datepicker).toHaveBeenAppliedOn(input#myDatePickerInput);

Is there any way to do so?

-Thanks.

**Comment by Jefferson-Faseler** [comment]
Hi @sadikr, if I am understanding your issue it seems like you want to know if there is a way to find out if the element handles some sort of event. If that is correct you could try the toHandleWith matcher. This matcher can be found in the readme and takes a handler function as the second param.

**Comment by sadikr** [comment]
@Jefferson-Faseler : Thanks for the help! Actually I have created my custom matcher, that works well :)
